spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
#  jpa:
#    defer-datasource-initialization: true
#    generate-ddl: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml