INSERT INTO BOOK(TITLE, ISBN, TOTAL_PAGES, PUBLISHED_DATE)
VALUES ('The Way of Kings', '3afasda', 500, '2019-10-01');
INSERT INTO BOOK(TITLE, ISBN, TOTAL_PAGES, PUBLISHED_DATE)
VALUES ('Words of Radiance', 'sdfweaff', 600, '2022-10-01');